// Tilt Maze — roll the ball to the goal. Tilt to steer, avoid the holes.
#include "pixeltilt/pixeltilt.h"

using namespace pt;

namespace {

// 16x16 cells, 4px each. '#' wall, 'S' start, 'G' goal, 'O' hole.
constexpr int GRID = 16;
constexpr int CELL = 4;

// Generated by a seeded recursive-backtracker (see tools/ docs); every level
// is BFS-verified solvable while avoiding all holes.
const char* LEVELS[][GRID] = {
    {
        "################",
        "#S#...........##",
        "#.###.#.########",
        "#.....#.......##",
        "###.#####.###.##",
        "#.#.....#.#...##",
        "#.#####.###.#.##",
        "#.....#...#.#.##",
        "#.##.####.#.####",
        "#.#.......#...##",
        "#...#########.##",
        "#.#.#.........##",
        "#.#.#####.###.##",
        "#.........#..G##",
        "################",
        "################",
    },
    {
        "################",
        "#S......#.....##",
        "###.###.#####.##",
        "#..O..#..O..#.##",
        "###.#.#.###.#.##",
        "#.....#.#.O.#.##",
        "#.###O#.#.###.##",
        "#.#.....#.....##",
        "#.###.#######.##",
        "#...#.....#...##",
        "#.#.#.#.#.#.#.##",
        "#.#.#.#.#.#...##",
        "#.#.#.#.#####.##",
        "#.#...#......G##",
        "################",
        "################",
    },
    {
        "################",
        "#S........#...##",
        "########..#O#.##",
        "#.#.......#...##",
        "#.#.#.#######.##",
        "#.#...........##",
        "#.###########.##",
        "#.O.O.......#.##",
        "#.#..########.##",
        "#.#.....#.....##",
        "#.#.###.#.######",
        "#..O#...#...#.##",
        "###.#O..###.#.##",
        "#O....#.O....G##",
        "################",
        "################",
    },
};
constexpr int LEVEL_COUNT = 3;

enum State { PLAYING, LEVEL_DONE, ALL_DONE };

State state;
int level;
int scoreRank;          // high-score table rank for this run, -1 if none
float px, py, vx, vy;   // ball position/velocity in pixels
float levelTime, totalTime;
float deathFlash;

char cellAt(int cx, int cy) {
  if (cx < 0 || cy < 0 || cx >= GRID || cy >= GRID) return '#';
  return LEVELS[level][cy][cx];
}

void findCell(char which, float& outX, float& outY) {
  for (int y = 0; y < GRID; y++)
    for (int x = 0; x < GRID; x++)
      if (cellAt(x, y) == which) {
        outX = x * CELL + CELL / 2.0f;
        outY = y * CELL + CELL / 2.0f;
        return;
      }
}

void resetBall() {
  findCell('S', px, py);
  vx = vy = 0;
}

void loadLevel(int n) {
  level = n;
  levelTime = 0;
  deathFlash = 0;
  state = PLAYING;
  resetBall();
}

void init() {
  setSfxStyle(STYLE_SOFT);
  music(MUS_CHILL);
  totalTime = 0;
  scoreRank = -1;
  loadLevel(0);
}

bool hitsWall(float x, float y) {
  constexpr float R = 1.4f;
  int x0 = floori((x - R) / CELL), x1 = floori((x + R) / CELL);
  int y0 = floori((y - R) / CELL), y1 = floori((y + R) / CELL);
  for (int cy = y0; cy <= y1; cy++)
    for (int cx = x0; cx <= x1; cx++) {
      if (cellAt(cx, cy) != '#') continue;
      // Circle vs cell AABB.
      float nx = clampf(x, cx * CELL, (cx + 1) * CELL);
      float ny = clampf(y, cy * CELL, (cy + 1) * CELL);
      float dx = x - nx, dy = y - ny;
      if (dx * dx + dy * dy < R * R) return true;
    }
  return false;
}

void draw() {
  clear();
  for (int y = 0; y < GRID; y++)
    for (int x = 0; x < GRID; x++) {
      char c = cellAt(x, y);
      if (c == '#') {
        fillRect(x * CELL, y * CELL, CELL, CELL, rgb(30, 40, 90));
        rect(x * CELL, y * CELL, CELL, CELL, rgb(50, 70, 150));
      } else if (c == 'O') {
        fillCircle(x * CELL + 1, y * CELL + 1, 1, rgb(10, 10, 10));
        circle(x * CELL + 1, y * CELL + 1, 1, rgb(70, 30, 30));
      } else if (c == 'G') {
        fillRect(x * CELL, y * CELL, CELL, CELL, rgb(10, 60, 20));
        rect(x * CELL, y * CELL, CELL, CELL, GREEN);
      }
    }

  if (deathFlash > 0) {
    fillCircle((int)px, (int)py, 2 + (int)(deathFlash * 8), rgb(180, 40, 20));
  }
  fillCircle((int)px, (int)py, 1, rgb(255, 220, 120));
  pixel((int)px, (int)py, WHITE);
}

void update(float dt) {
  if (state == LEVEL_DONE) {
    draw();
    fillRect(6, 22, 52, 20, rgb(8, 8, 20));
    rect(6, 22, 52, 20, GREEN);
    textCentered(25, "LEVEL", WHITE);
    textCentered(31, "CLEAR!", GREEN);
    if (input.justDown(BTN_CLICK)) { sfx(SFX_SELECT); loadLevel(level + 1); }
    return;
  }
  if (state == ALL_DONE) {
    clear();
    textCentered(14, "YOU WIN!", hsv(totalTime * 90, 0.9f, 1.0f));
    char buf[16];
    int secs = (int)totalTime;
    // tiny int->str
    int i = 0;
    if (secs >= 100) buf[i++] = '0' + (secs / 100) % 10;
    if (secs >= 10) buf[i++] = '0' + (secs / 10) % 10;
    buf[i++] = '0' + secs % 10;
    buf[i++] = 'S';
    buf[i] = 0;
    textCentered(28, "TIME", GRAY);
    textCentered(36, buf, WHITE);
    if (scoreRank == 0) textCentered(44, "NEW BEST!", YELLOW);
    textCentered(52, "CLICK - RETRY", DARKGRAY);
    if (input.justDown(BTN_CLICK)) init();
    return;
  }

  levelTime += dt;
  totalTime += dt;
  if (deathFlash > 0) deathFlash -= dt;

  // Tilt drives acceleration; light damping so the ball settles. The small
  // deadzone keeps the ball from creeping when the board sits almost level.
  constexpr float ACCEL = 95.0f;
  constexpr float DAMP = 1.6f;
  vx += tiltCurve(input.tiltX, 0.05f) * ACCEL * dt;
  vy += tiltCurve(input.tiltY, 0.05f) * ACCEL * dt;
  vx -= vx * DAMP * dt;
  vy -= vy * DAMP * dt;

  // Per-axis movement with wall collision (kills velocity on impact axis).
  float nx = px + vx * dt;
  if (hitsWall(nx, py)) { if (fabsf_(vx) > 24.0f) sfx(SFX_BOUNCE, 1.2f); vx = -vx * 0.25f; } else px = nx;
  float ny = py + vy * dt;
  if (hitsWall(px, ny)) { if (fabsf_(vy) > 24.0f) sfx(SFX_BOUNCE, 1.2f); vy = -vy * 0.25f; } else py = ny;

  // Holes and goal trigger from the cell under the ball center.
  char under = cellAt(floori(px / CELL), floori(py / CELL));
  if (under == 'O') {
    sfx(SFX_HURT);
    deathFlash = 0.4f;
    resetBall();
  } else if (under == 'G') {
    if (level + 1 >= LEVEL_COUNT) {
      state = ALL_DONE;
      sfx(SFX_WIN);
      scoreRank = submitScore((int)(totalTime * 10.0f));  // deciseconds
    } else {
      state = LEVEL_DONE;
      sfx(SFX_POWERUP);
    }
  }

  draw();
}

}  // namespace

PT_GAME_SCORED(tilt_maze, "TILT MAZE", init, update, pt::SCORE_TIME)
