// Scans games/*/game.cpp for PT_GAME(...) and regenerates
// games/generated/game_list.cpp, which is what links every game into the
// engine's menu on both platforms. Runs automatically from the wasm build,
// the PlatformIO pre-script, and new-game.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const gamesDir = join(root, "games");

export function generate() {
  const entries = [];
  for (const name of readdirSync(gamesDir, { withFileTypes: true })) {
    if (!name.isDirectory() || name.name.startsWith("_") || name.name === "generated") continue;
    const src = join(gamesDir, name.name, "game.cpp");
    if (!existsSync(src)) continue;
    const code = readFileSync(src, "utf8");
    const m = code.match(/PT_GAME(?:_SCORED)?\s*\(\s*([A-Za-z0-9_]+)\s*,/);
    if (!m) {
      console.warn(`warning: ${name.name}/game.cpp has no PT_GAME(...) — skipped`);
      continue;
    }
    if (m[1] !== name.name) {
      console.warn(`warning: ${name.name}/game.cpp registers id '${m[1]}' (expected '${name.name}')`);
    }
    entries.push(m[1]);
  }
  entries.sort();

  const out = [
    "// AUTO-GENERATED by tools/gen-games.mjs — do not edit by hand.",
    "// Regenerate with `npm run gen` (also runs as part of every build).",
    '#include "pixeltilt/game.h"',
    "",
    ...entries.map((id) => `extern const pt::Game pt_game_${id};`),
    "",
    "namespace pt {",
    "const Game* const GAME_LIST[] = {",
    ...entries.map((id) => `    &pt_game_${id},`),
    "};",
    `const int GAME_COUNT = ${entries.length};`,
    "}  // namespace pt",
    "",
  ].join("\n");

  const outDir = join(gamesDir, "generated");
  mkdirSync(outDir, { recursive: true });
  const outFile = join(outDir, "game_list.cpp");
  const prev = existsSync(outFile) ? readFileSync(outFile, "utf8") : "";
  if (prev !== out) {
    writeFileSync(outFile, out);
    console.log(`game_list.cpp: ${entries.length} game(s): ${entries.join(", ")}`);
  }
  return entries;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) generate();
