// Scans games/*/game.cpp for a PT_GAME registration and regenerates
// games/generated/game_list.cpp, which is what links every game into the
// engine's menu on both platforms. Runs automatically from the wasm build,
// the PlatformIO pre-script, and new-game.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const gamesDir = join(root, "games");

export function generate() {
  const entries = [];
  for (const name of readdirSync(gamesDir, { withFileTypes: true })) {
    if (!name.isDirectory() || name.name.startsWith("_") || name.name === "generated") continue;
    const src = join(gamesDir, name.name, "game.cpp");
    if (!existsSync(src)) continue;
    const code = readFileSync(src, "utf8");
    // Registrations are standalone declarations. Anchoring avoids treating a
    // commented example, string literal or helper-macro body as the game.
    const matches = [...code.matchAll(/^[ \t]*(PT_GAME(?:_SCORED|_UNSCORED)?)[ \t]*\([ \t]*([A-Za-z0-9_]+)[ \t]*,/gm)];
    if (matches.length === 0) {
      console.warn(`warning: ${name.name}/game.cpp has no PT_GAME registration — skipped`);
      continue;
    }
    if (matches.length !== 1) {
      throw new Error(`${name.name}/game.cpp must have exactly one PT_GAME registration`);
    }
    const m = matches[0];
    const id = m[2];
    if (id !== name.name) {
      throw new Error(`${name.name}/game.cpp registers id '${id}' (expected '${name.name}')`);
    }
    entries.push({ id, scored: m[1] !== "PT_GAME_UNSCORED" });
  }
  entries.sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
  const ids = entries.map((entry) => entry.id);
  const scoredCount = entries.filter((entry) => entry.scored).length;

  const out = [
    "// AUTO-GENERATED by tools/gen-games.mjs — do not edit by hand.",
    "// Regenerate with `npm run gen` (also runs as part of every build).",
    '#include "pixeltilt/game.h"',
    '#include "pixeltilt/storage.h"',
    "",
    ...ids.map((id) => `extern const pt::Game pt_game_${id};`),
    "",
    "namespace pt {",
    "const Game* const GAME_LIST[] = {",
    ...ids.map((id) => `    &pt_game_${id},`),
    "};",
    `const int GAME_COUNT = ${entries.length};`,
    `const int SCORED_GAME_COUNT = ${scoredCount};`,
    `static_assert(${scoredCount} <= SCORE_GAME_CAPACITY,`,
    '              "scored game registry exceeds persistent score capacity");',
    "}  // namespace pt",
    "",
  ].join("\n");

  const outDir = join(gamesDir, "generated");
  mkdirSync(outDir, { recursive: true });
  const outFile = join(outDir, "game_list.cpp");
  const prev = existsSync(outFile) ? readFileSync(outFile, "utf8") : "";
  if (prev !== out) {
    writeFileSync(outFile, out);
    console.log(`game_list.cpp: ${entries.length} game(s), ${scoredCount} scored: ${ids.join(", ")}`);
  }
  return ids;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) generate();
