# PlatformIO pre-build hook: refresh games/generated/game_list.cpp so newly
# added games are linked in without a manual `npm run gen`, and embed any
# assets/music/*.pta files into firmware/src/generated_music.h so converted
# songs (Audio Lab -> download .pta) play on the device.
import shutil
import subprocess
import os

Import("env")  # noqa: F821 (provided by PlatformIO's SCons environment)

project_dir = env["PROJECT_DIR"]  # noqa: F821
node = shutil.which("node")
generated = os.path.join(project_dir, "games", "generated", "game_list.cpp")

if node:
    subprocess.run([node, os.path.join("tools", "gen-games.mjs")], cwd=project_dir, check=True)
elif not os.path.exists(generated):
    raise SystemExit(
        "games/generated/game_list.cpp is missing and node is not installed; "
        "run `npm run gen` once on a machine with Node.js"
    )

# --- embed background-music PTA files ---------------------------------------
# assets/music/<track>.pta (track = menu/chill/action/tense/wiz3/rave/
# rave_acid/rave_dodgems) overrides the
# built-in chiptune for that pt::MusicTrack on the device, mirroring the
# emulator's localStorage overrides. Arrays live in flash (const), so size is
# effectively a non-issue on the 16 MB part.

TRACKS = [
    "none", "menu", "chill", "action", "tense",
    "wiz3", "rave", "rave_acid", "rave_dodgems",
]  # index = pt::MusicTrack
music_dir = os.path.join(project_dir, "assets", "music")
out_path = os.path.join(project_dir, "firmware", "src", "generated_music.h")

lines = [
    "#pragma once",
    "// AUTO-GENERATED by firmware/gen_games.py from assets/music/*.pta — do not",
    "// edit. Index matches pt::MusicTrack; nullptr = play the built-in chiptune.",
    "#include <stdint.h>",
    "",
]
ptrs = []
lens = []
for i, name in enumerate(TRACKS):
    path = os.path.join(music_dir, name + ".pta")
    if i == 0 or not os.path.isfile(path):
        ptrs.append("nullptr")
        lens.append("0")
        continue
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"PTA1":
        raise SystemExit(f"{path} is not a PTA file (bad magic)")
    array = f"MUSIC_PTA_{name.upper()}"
    lines.append(f"static const uint8_t {array}[] = {{  // {len(data)} bytes")
    for off in range(0, len(data), 24):
        chunk = ",".join(str(b) for b in data[off:off + 24])
        lines.append(f"  {chunk},")
    lines.append("};")
    ptrs.append(array)
    lens.append(f"sizeof({array})")
    print(f"gen_games: embedded {os.path.relpath(path, project_dir)} ({len(data)} bytes)")

lines += [
    "",
    "static const uint8_t* const MUSIC_PTA[] = {" + ", ".join(ptrs) + "};",
    "static const uint32_t MUSIC_PTA_LEN[] = {" + ", ".join(lens) + "};",
    "",
]
content = "\n".join(lines)

previous = None
if os.path.exists(out_path):
    with open(out_path, "r") as f:
        previous = f.read()
if content != previous:  # don't dirty the build when nothing changed
    with open(out_path, "w") as f:
        f.write(content)
